# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.2.1.dev33+gc6715da.d20230301'
__version_tuple__ = version_tuple = (1, 2, 1, 'dev33', 'gc6715da.d20230301')
